### ISSUE TITLE
User account creation with temporary password in email.

### ISSUE THREAD

**Issue by dealproc** [brockallen/BrockAllen.MembershipReboot#141]
Feature Request: Would be nice to issue the email with a temporary password that we can force the user to change at their first login.

**Comment by robertorodes** [comment]
Hello @brockallen and everyone else,

I know this issue was opened quite a while ago but currently I am facing a similar scenario to the one  @keithharvey talked about in his comment (the basecamp.com example). Basically, I need to implement an invitations based onboarding process (closed registration) through which users will only be allowed to signup with an invitation. Obviously, this is something quite usual in many applications, mainly in their first market stage as a mechanism to grow their user base in a controlled way.

I've been working with MR for a quite a while (together with Thinktecture Identity Server 3) and read its related documentation but I have not been able to find the way to support this use case, although @keithharvey in his comment mentions it is really supported.

Any explanation or hints about how to implement this behavior if actually possible would be really appreciated.

Thank you all in advance and best regards.

**Comment by brockallen** [comment]
Something like an invitation code you might need to build yourself. Then once the user has arrived via the code you can walk them thru the account creation process, and since you're confident that they are in control of the email that you sent the code to, I'd say you can mark the email as verified.

**Comment by robertorodes** [comment]
Ok, that's what I wanted to know. Thanks a lot for your help.

**Comment by SeriousM** [comment]
> Ok, that's what I wanted to know. Thanks a lot for your help.

Hi @robertorodes,
could you provice a bit of code or steps to be done to implement the invitation process?
Or didn't you implemented it?

Thank you very much!!
