### ISSUE TITLE
Error when trying to remove claim with the latest version of EF

### ISSUE THREAD

**Issue by domtheluck** [brockallen/BrockAllen.MembershipReboot#340]
Hi,

Got this error when I try to remove a claim with the latest version of EF (6.1.30225):

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.InvalidOperationException: The operation failed: The relationship could not be changed because one or more of the foreign-key properties is non-nullable. When a change is made to a relationship, the related foreign-key property is set to a null value. If the foreign-key does not support null values, a new relationship must be defined, the foreign-key property must be assigned another non-null value, or the unrelated object must be deleted.

Source Error:

Line 60:         protected virtual void SaveChanges()
Line 61:         {
Line 62:             db.SaveChanges();
Line 63:         }
Line 64:

**Comment by Danthar** [comment]
Just for kicks: I have the exact same issue.
And yes I have added the RegisterUserAccountChildTablesForDelete and I have not changed anything concerning lazyloading or such.

It seems to be related to the latest EF version (6.1) Its easy to reproduce as well. Checkout the customization sample from github. Try to register an account and stuff starts failing.

**Comment by brockallen** [comment]
Ugg, ok. I'll look into it. Thx.

**Comment by Danthar** [comment]
Ah. I just came to the exact conclusion as AlonCG did in his referenced issue. Shall we continue this in there? Due to that issue being more relevant to the problem at hand ?

**Comment by brockallen** [comment]
Well, do whatever you can to determine what the real issue is -- I don't have a lot of time, so if you figure it out sooner then that's help all of us.

**Comment by Danthar** [comment]
Ok ill stay in this thread then. 
Here is what I found out:

When using the current source, build against the latest EF (6.1.2). It works. My previous attempts failed due to unrelated issues, which weren't immediately clear due to EF mucking up Exceptions.

So then I started comparing stuff. A few things became clear quite fast.
- The nuget packages still use the RelationalUserAccount with the generic key. Where the current source does not.
- The RegisterUserAccountChildTablesForDelete is gone.
And so a few other things. For example: useraccount name validation has been tightened. (no more spaces! aww...)

So I updated my project to use the latest source build. And after fixing some EF "database changed" troubles, stuff works now.

So sorry for scaring you by necromancing this issue back from the dead. But I am actually more then curious as to what the fundamental change was that fixed this issue?

And I advice updating the nuget packages, it will save new users quite abit of grief.
