### ISSUE TITLE
Account verification email 

### ISSUE THREAD

**Issue by rsmolnikov** [brockallen/BrockAllen.MembershipReboot#351]
Why account verification email is send even if RequireAccountVerification was set to false?
And if I call ResetPassword, EmailChangeRequestedEvent is send instead of PasswordResetRequestedEvent.
What is expected behavior? Can I set account to be verified automatically on first login?

Thanks,
Roman.

**Comment by TheOtherOnes** [comment]
I still don't understand why EmailChangeRequestedEvent email is sent and not the PasswordResetRequestedEvent email when ResetPassword is called.

**Comment by brockallen** [comment]
IIRC if they've never verified their email then that triggers the initial 'welcome' style message.

**Comment by TheOtherOnes** [comment]
The 'Welcome' message would be AccountCreatedEvent, wouldn't it?  The one that is being sent EmailChangeRequestedEvent which requires me to enter my password (which I've just asked to reset because I forgot it).  

The text of the EmailChangeRequestedEvent email isn't appropriate for a request to verify an email address.  Plus, the web page is asking you to enter your password.  How can you if you've just asked to reset it?

I see that you are saying that the email verification is still required after account creation.  If users can ignore it (because RequireAccountVerification is false), they are likely to.  In fact, the problem is that I took out the {confirmChangeEmailUrl} from the AccountCreatedEvent_body because it didn't seem to be necessary.  I guess now it is.  

Is there any way to disable the need to verify the email?  My UX guy is the one who required that I take it out.

Adam

**Comment by brockallen** [comment]
You're correct about the welcome -- I was going from memory, so I had to look thru the code again.

You can't reset a password unless the email has been verified. So anytime you request email reset and the account's email has not been verified then it sends the email confirmation event. 

The RequireAccountVerification flag is poorly named. It means if the email is not verified then don't let the user login.

**Comment by TheOtherOnes** [comment]
Thanks, but the problem now is that the wrong event is fired.  EmailChangeRequestedEvent is fired when AccountCreatedEvent is fired.  Any chance this will be fixed?

**Comment by brockallen** [comment]
Mind forking and writing a unit test to show the problem?

**Comment by TheOtherOnes** [comment]
I'm embarrassed to say that I have never done that and don't really know how.

**Comment by brockallen** [comment]
Well, there's a unit test project in the source that exercises the methods to prove they work the way they're expected to work. Perhaps it's a chance to learn how to do that.

**Comment by TheOtherOnes** [comment]
I think I found the issue. It's in VerificationKeyPurpose.cs.  You've commented out VerifyAccount and when a user registers, ChangeEmail (3) is stored as the VerificationKeyPurpose in the database.  That's why later, when the user attempts to change their password they get a ChangeEmail email.

namespace BrockAllen.MembershipReboot
{
    public enum VerificationKeyPurpose
    {
        //VerifyAccount = 1,
        ResetPassword = 2,
        ChangeEmail = 3,
        ChangeMobile = 4
    }
}

**Comment by brockallen** [comment]
Yes, at some point I made the design change that verify is the same as a change email. You can always check in the email verification event handler to see if the email is yet verified to know if it's the first time. But there's also an account created event for the initial email.
