### ISSUE TITLE
Close account vs. IsLoginAllowed

### ISSUE THREAD

**Issue by stevenfirstrowinc** [brockallen/BrockAllen.MembershipReboot#475]
Hi,

Is there any fundamental difference between Closing an account and setting IsLoginAllowed = false?  Other than when the settings delete closed accounts that is.  A quick review of the code looks like they essentially give the same result; user can't login.  Is there more to it or is it primarily syntactical?

**Comment by stevenfirstrowinc** [comment]
Thanks for the response.  I'll update my code to use IsLoginAllowed.  I think that makes more sense to me.

**Comment by woodwardmatt** [comment]
Just working through this area of MR myself at the moment. I think the confusion creeps in because you expect that when you close an account the user shouldn't be able to login (but OOTB they still can). It feels that given the option to either close or delete that: 

* Delete should permanently delete the user account data
* Close should flag the account as closed (which it does) *and* suspend access rights i.e. no login allowed.

As it stands at this point the `account.IsLoginAllowed = false` isn't implemented as part of the account closure routine so you have to do this independantly using `SetIsLoginAllowed(Guid accountID, bool isLoginAllowed)`. 

Whilst this provides complete flexibility to do as you please within your own application, maybe an override on the `userAccountService.CloseAccount()` method to provision for an IsLoginAllowed boolean parameter may help to smooth out the implementation for some :)

Just my two cents worth on an old thread :)
