### ISSUE TITLE
Need alternate method(s) to validate/verify new uses when email fails

### ISSUE THREAD

**Issue by StateBarofArizona** [brockallen/BrockAllen.MembershipReboot#493]
Suggestion for future version:  We have users that try as they might, white list, etc., they never seem to receive our emails in order to click the validation link.  What other methods could be used to confirm their identity as a valid user and allow them access?

**Comment by brockallen** [comment]
You can also send the code in the email and provide a UI for them to enter said code. IIRC, one of the samples has this.

**Comment by StateBarofArizona** [comment]
The problem is they are not getting any emails from our system.  We have yet to figure out if we are being blocked as spam due to volume, content or other?  Most users get the emails.  Some behind corporate firewalls or, ahem, still using AOL or other older systems don't receive the MR messages but they claim they get personal messages.

**Comment by brockallen** [comment]
So ensure the email is actually being sent (and not an error in some way). 

Email is what the entire security model relies upon for validating users so that they can reset password at some point. If you don't care about secure password reset, then you can disable the "require account verification" to let them login before email is verified.

**Comment by brockallen** [comment]
any update?

**Comment by StateBarofArizona** [comment]
No change.  Go ahead and close as informational, discussion for a later date.
