### ISSUE TITLE
Add IP address to UserAccountEvent<TAccount>

### ISSUE THREAD

**Issue by kendaleiv** [brockallen/BrockAllen.MembershipReboot#537]
Ideally, the IP address (and, possibly other information from the request) would be available when handling events.

The use case is auditing: We have access to the account information, but, while handling an event I don't see a way to access the IP address. Using `HttpContext.Current` might work, but I haven't tried it -- it's not an ideal solution anyhow...

Would this unnecessarily bloat the events? Should this use case be accomplished a different way?

**Comment by brockallen** [comment]
Hmm, yea... I think this would require a change to how the events are deigned -- they'd need to be injected/instantiated on every request. You could, of course, change the Di system to create them on every request when you provide the MR Config.

**Comment by dealproc** [comment]
The only issue I see with relying on `HttpContext.Current` is two folds:

1) When you are not using the MembershipReboot system on a web application
2) When you are working within the Owin context, and `HttpContext.Current` is unavailable.

Would it be more advisable to create some sort of interface, so that the `SystemWeb` package gets the ability to ping HttpContext.Current, the `Owin` package gets to play within the IOwinContext as necessary, and outside of those two mainstream use-cases, *I think* that the developer should be responsible for implementing the required interface to resolve the pertinent information that matches their scenario (or default to empty/nulls as necessary)

**Comment by brockallen** [comment]
For OWIN there's a non-System.Web implementation (see: the MembershipReboot.Owin project).

**Comment by brockallen** [comment]
All set with this issue?

**Comment by kendaleiv** [comment]
I'm good with closing for now. Thanks!
