### ISSUE TITLE
Looking for contributors for documentation :)

### ISSUE THREAD

**Issue by brockallen** [brockallen/BrockAllen.MembershipReboot#84]
I think the biggest thing missing right now is basic documentation for MR. If anyone, while they're going thru the pains of learning how MR works, is interested in contributing anything then I'd be happy to edit and post on a wiki or somewhere as the formal docs for MR. 

Ping me (here or via email) if anyone is interested. 

Edit: see, this is why I need contributors -- i can't spell :/

**Comment by dealproc** [comment]
Are you still accepting pull requests for documentation?  I'm in the process of setting up the email generation portion of MR on a client product, and it's a painful experience because of the cross-referencing back to the User Service on when each event is fired.

I'm not saying what I'll provide would be perfect, but it'd be a start that may make it easier for the inline docs to then be finessed as required.

**Comment by brockallen** [comment]
Sure -- anything you want to provide I'll put up int he wiki.
